# Generated by Django 5.1.4 on 2025-01-06 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Locomotive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=5)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('CLW', 'Clockwise'), ('ACW', 'Anticlockwise')], default='CLW', max_length=3)),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.load')),
            ],
        ),
        migrations.CreateModel(
            name='TrainLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.location')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.train')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='location',
            name='trains',
            field=models.ManyToManyField(through='storage.TrainLocation', to='storage.train'),
        ),
        migrations.CreateModel(
            name='TrainLocomotive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('locomotive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.locomotive')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.train')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='train',
            name='locomotives',
            field=models.ManyToManyField(through='storage.TrainLocomotive', to='storage.locomotive'),
        ),
    ]
