# Generated by Django 5.1.4 on 2025-01-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='load',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='locomotive',
            options={'ordering': ('description', 'number')},
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
